default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: appinfluencer
  host: localhost
  port: 5432

development:
  <<: *default
  database: influencer_app_development

test:
  <<: *default
  database: influencer_app_test

production:
  <<: *default
  database: influencer_app_production
  username: influencer_app
  password: <%= ENV["INFLUENCER_APP_DATABASE_PASSWORD"] %>